version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pwd123

    volumes:
      - /d/sn-mysql:/var/lib/mysql  # 本地 SSD 位置
    networks:
      - app-network
    ports:
      - "3306:3306"
    restart: always

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pwd123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:  # 用於將 MySQL 資料存放於 SSD 的位置

networks:
  app-network: