name: Deploy to Docker

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    # 只在 PR 被合併時執行，而不是被關閉時
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          
      - name: Configure Git safe directory
        shell: powershell
        run: |
          & "C:\Users\A1477\AppData\Local\Programs\Git\cmd\git.exe" config --global --add safe.directory C:/Users/A1477/Desktop/project/sn-nodejs-api
          
      - name: Navigate and Deploy
        shell: powershell
        run: |
          cd "C:\Users\A1477\Desktop\project\sn-nodejs-api"
          & "C:\Users\A1477\AppData\Local\Programs\Git\cmd\git.exe" pull origin main
          docker-compose up --build -d