name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          
      - name: Configure Git safe directory
        shell: powershell
        run: |
          & "C:\Program Files\Git\cmd\git.exe" config --global --add safe.directory C:/Users/A1477/Desktop/project/sn-nodejs-api
          
      - name: Navigate and Deploy
        shell: powershell
        run: |
          cd "C:\Users\A1477\Desktop\project\sn-nodejs-api"
          & "C:\Program Files\Git\cmd\git.exe" pull origin main
          docker-compose up --build -d