name: Deploy to Docker

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev
          
      - name: Configure Git safe directory
        shell: powershell
        run: |
          git config --global --add safe.directory "C:/Users/A1477/Desktop/project/sn-nodejs-api"
          
      - name: Navigate and Deploy
        shell: powershell
        run: |
          cd "C:\Users\A1477\Desktop\project\sn-nodejs-api"
          git pull origin dev
          docker-compose up --build -d