name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]
    
    steps:
      - name: Navigate to project directory
        run: |
          cd "C:\Users\A1477\Desktop\project\sn-nodejs-api"
          
      - name: Pull latest changes
        run: |
          git pull origin main
          
      - name: Build and deploy Docker containers
        run: |
          docker-compose up --build -d