name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]  # 如果您的 runner 是 Linux 系統
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
            cd "C:\Users\A1477\Desktop\project\sn-nodejs-api"
            docker-compose up --build -d